name: thingspeak_visualizer
description: A powerful and lightweight data visualizer for ThingSpeak channels.
version: 1.2.0
publish_to: 'none'

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter


  fl_chart: ^0.69.0
  http: ^1.2.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.1
  
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  package_info_plus: ^9.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  # ESTA ES LA L√çNEA QUE TE FALTA (La ruta global)
  image_path: "assets/icon/launcher_icon.png"

  # Android
  android: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/launcher_icon.png"
  
  # iOS
  ios: true
  
  # Web
  web:
    generate: true
    image_path: "assets/icon/launcher_icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  
  # Windows
  windows:
    generate: true
    image_path: "assets/icon/launcher_icon.png"
    icon_size: 256